<a href="https://colab.research.google.com/github/Pager07/TensorflowSpecialization/blob/master/C4W2_CreatingTimeDataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DataSet

In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#Creating Dataset object
dataset = tf.data.Dataset.range(10)
for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [13]:
#Making a window dataset
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=' ')
  print()


0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [15]:
#Making a windowed dataset, where we remove value that don't fit in the window
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1 ,drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=' ')
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [28]:
#Converting dataset to numpy
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())

0
1
2
3
4
5
6
7
8
9


In [33]:
#Create a x,y label
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1],window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [36]:
#Shuffling the dataset
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window :(window[:-1] , window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy() , y.numpy())

[4 5 6 7] [8]
[0 1 2 3] [4]
[2 3 4 5] [6]
[3 4 5 6] [7]
[1 2 3 4] [5]
[5 6 7 8] [9]


In [37]:
#Setting batch size of 2
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window :(window[:-1] , window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print(x.numpy() , y.numpy())

[[2 3 4 5]
 [4 5 6 7]] [[6]
 [8]]
[[3 4 5 6]
 [1 2 3 4]] [[7]
 [5]]
[[5 6 7 8]
 [0 1 2 3]] [[9]
 [4]]
